site_name: Galaxea Docs
site_url: https://userguide-galaxea.github.io/userguide-galaxea/
repo_url: https://github.com/userguide-galaxea/userguide-galaxea
site_description: "Galaxea"
copyright: Copyright &copy; 2023 - 2025 Galaxea
site_author: Galaxea Inc

theme:
    name: material
    logo: assets/logo.png
    palette:
        primary: black
plugins:
    - search:
        enabled: true
features:
    - search.highlight
    - search.inline
    - search.excerpt
    - navigation.expand
nav:
  - Galaxea Docs: index.md
  - Pre-sales documentation:
      - About us: pre_sales_documention/introduction.md
      - A1: pre_sales_documention/product_info/A1.md
      - R1: pre_sales_documention/product_info/R1.md
      - X1: pre_sales_documention/product_info/X1.md


extra_css:
  - styles.css
  - pre_sales_documention/simple_intro.css
  - pre_sales_documention/detail_intro.css

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences